  spring:
    data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: test_db
      port: 27017
      host: localhost
      uri: mongodb://root:root@localhost:27017/test_db